### ISSUE TITLE
Multiple mode kit

### ISSUE THREAD

**Issue by LorenzooG** [nekkan/FossSkyWars#1]
What happen if you want to set many modes in a kit? You should create a new? I suggest you to use an array instead a single value:

```yaml

  - name: Scout
    display_icon: "diamond_sword"
    mode: 
    - solo
    - team
    - ranked
    price: 10000
    items:
      - material: "stone_sword"

      - material: "potion"
        display_name: "Scout (x3)"
        type: "speed"
        amount: 3
        splash: true
        duration: 30

```
